site_name: libcpprime Documentation
site_url: https://sortA0329.github.io/libcpprime/
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - content.code.copy
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
repo_url: https://github.com/sortA0329/libcpprime
repo_name: sortA0329/libcpprime
copyright: "Copyright © 2026 sortA"
nav:
  - libcpprime: index.md
  - "GitHub Repository": https://github.com/sortA0329/libcpprime
markdown_extensions:
  - tables
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.magiclink
plugins:
  - search
  - optimize
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
