name: Test

on:
    push:
    workflow_dispatch:

jobs:
    test_old_gcc:
        name: Run Test (old g++ / ubuntu)
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                gcc: [5, 6, 7, 8]
                cpp: ["17"]
                include:
                    - gcc: 5
                      cpp: "11"
                    - gcc: 5
                      cpp: "14"

                    - gcc: 8
                      cpp: "2a"
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Update apt
              run: sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic main universe" && sudo apt-get update
            - name: Install g++${{ matrix.gcc }}
              run: sudo apt-get install g++-${{ matrix.gcc }}
            - name: Run build on C++${{ matrix.cpp }}
              run: g++-${{ matrix.gcc }} -std=c++${{ matrix.cpp }} -Wall -Wextra -O3 -march=native -I. -o ./tests/tests-gcc-${{ matrix.gcc }}-${{ matrix.cpp }}.out ./tests/tests.cpp
            - name: Run tests
              run: ./tests/tests-gcc-${{matrix.gcc}}-${{ matrix.cpp }}.out

    test_gcc:
        name: Run Test (g++ / ubuntu)
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                gcc: [9, 10, 11, 12, 13, 14]
                cpp: ["2a"]
                include:
                    - gcc: 11
                      cpp: "23"

                    - gcc: 12
                      cpp: "23"

                    - gcc: 13
                      cpp: "23"

                    - gcc: 14
                      cpp: "23"
                    - gcc: 14
                      cpp: "26"
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Update apt
              run: sudo apt update && sudo apt install build-essential
            - name: Install g++${{ matrix.gcc }}
              run: sudo apt install g++-${{ matrix.gcc }}
            - name: Run build on C++${{ matrix.cpp }}
              run: g++-${{ matrix.gcc }} -std=c++${{ matrix.cpp }} -Wall -Wextra -O3 -march=native -fconstexpr-depth=2147483647 -fconstexpr-loop-limit=2147483647 -fconstexpr-ops-limit=2147483647 -I. -o ./tests/tests-gcc-${{ matrix.gcc }}-${{ matrix.cpp }}.out ./tests/tests.cpp
            - name: Run tests
              run: ./tests/tests-gcc-${{matrix.gcc}}-${{ matrix.cpp }}.out

    test_clang:
        name: Run Test (clang++ / ubuntu)
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                clang: [14, 15, 16, 17, 18]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Update apt
              run: sudo apt update
            - name: Install clang++${{ matrix.clang }}
              run: sudo apt install clang-${{ matrix.clang }}
            - name: Run build on C++20
              run: clang++-${{ matrix.clang }} -std=c++2a -Wall -Wextra -O3 -march=native -fconstexpr-depth=2147483647 -fconstexpr-steps=2147483647 -I. -o ./tests/tests-clang-${{ matrix.clang }}.out ./tests/tests.cpp
            - name: Run tests
              run: ./tests/tests-clang-${{ matrix.clang }}.out
